# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: botvalue.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='botvalue.proto',
  package='',
  serialized_pb='\n\x0e\x62otvalue.proto\"i\n\x07\x62otdata\x12\r\n\x05\x62otid\x18\x01 \x01(\x05\x12\n\n\x02v1\x18\x02 \x02(\x05\x12\n\n\x02v2\x18\x03 \x02(\x05\x12\n\n\x02v3\x18\x04 \x02(\x05\x12\n\n\x02v4\x18\x05 \x02(\x05\x12\x0f\n\x07\x62\x61tstat\x18\x06 \x01(\x05\x12\x0e\n\x06\x63\x61pvol\x18\x07 \x01(\x05')




_BOTDATA = _descriptor.Descriptor(
  name='botdata',
  full_name='botdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='botid', full_name='botdata.botid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v1', full_name='botdata.v1', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v2', full_name='botdata.v2', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v3', full_name='botdata.v3', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v4', full_name='botdata.v4', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batstat', full_name='botdata.batstat', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capvol', full_name='botdata.capvol', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['botdata'] = _BOTDATA

class botdata(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOTDATA

  # @@protoc_insertion_point(class_scope:botdata)


# @@protoc_insertion_point(module_scope)
